sudo: required
services:
   - docker

before_install:
   - docker build -t magnusfahlin/deploydemo -f Dockerfile.dev .

script:
   - docker run -e CI=true magnusfahlin/deploydemo npm run test

deploy:
   edge: true
   provider: elasticbeanstalk
   region: "eu-north-1"
   app: "DeployDemo"
   env: "Deploydemo-env"
   bucket_name: "elasticbeanstalk-eu-north-1-909875351047"
   bucket_path: "DeployDemo"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
      secure: $AWS_SECRET_KEY